{
 "title": "Attestation Processing",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Attestation Processing Metrics\n\nMetrics regarding `BeaconChain::process_attestation`, which processes `Attestation` from the network (but not in blocks).\n\nCollected from the [`beacon_chain`](https://github.com/sigp/lighthouse/tree/master/beacon_node/beacon_chain) crate.\n\n\n\n"
   },
   "content": "\n# Attestation Processing Metrics\n\nMetrics regarding `BeaconChain::process_attestation`, which processes `Attestation` from the network (but not in blocks).\n\nCollected from the [`beacon_chain`](https://github.com/sigp/lighthouse/tree/master/beacon_node/beacon_chain) crate.\n\n\n\n"
  },
  {
   "title": "Previous Epoch Attesting Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of Balance" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_attester"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "\n### Gossip Verification Times\n\n\nTimes to verify the attestation before re-gossiping\n"
   },
   "content": "\n### Gossip Verification Times\n\n\nTimes to verify the attestation before re-gossiping\n"
  },
  {
   "title": "Aggregated Attn Gossip Verification Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_aggregated_attestation_gossip_verification_seconds_sum[5m])\n/\nrate(beacon_aggregated_attestation_gossip_verification_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Unaggregated Attn Gossip Verification Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_unaggregated_attestation_gossip_verification_seconds_sum[5m])\n/\nrate(beacon_unaggregated_attestation_gossip_verification_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Aggregated Attn Gossip Verification Times",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(beacon_aggregated_attestation_gossip_verification_seconds_sum[5m])\n/\nrate(beacon_aggregated_attestation_gossip_verification_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Unaggregated Attn Gossip Verification Times",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(beacon_unaggregated_attestation_gossip_verification_seconds_sum[5m])\n/\nrate(beacon_unaggregated_attestation_gossip_verification_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "\n### Storing Attestation\n\nTimes to store the attestation in fork choice or pools.\n"
   },
   "content": "\n### Storing Attestation\n\nTimes to store the attestation in fork choice or pools.\n"
  },
  {
   "title": "Apply Attestation to Fork Choice",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_apply_to_fork_choice_sum[5m])\n/\nrate(beacon_attestation_processing_apply_to_fork_choice_count[5m])"
    }
   ]
  },
  {
   "title": "Apply Aggregate to Aggregation Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_apply_to_agg_pool_sum[5m])\n/\nrate(beacon_attestation_processing_apply_to_agg_pool_count[5m])"
    }
   ]
  },
  {
   "title": "Apply Aggregate to Op Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_apply_to_op_pool_sum[5m])\n/\nrate(beacon_attestation_processing_apply_to_op_pool_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "\n### Component Verification Times\n\n\nTimes to verify specific components of attestations\n"
   },
   "content": "\n### Component Verification Times\n\n\nTimes to verify specific components of attestations\n"
  },
  {
   "title": "Attestation Signature Verification Setup Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_signature_setup_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_signature_setup_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Attestation Signature Verification Setup Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_signature_setup_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_signature_setup_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Attestation Signature Verification Time",
   "type": "graph",
   "description": "This is the time it takes to do just the BLS verification function (e.g., adding public keys, doing pairings, etc)",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_signature_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_signature_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Agg. Pool Signature Aggregation Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_agg_pool_aggregation_sum[5m])\n/\nrate(beacon_attestation_processing_agg_pool_aggregation_count[5m])"
    }
   ]
  },
  {
   "title": "Attestation State Skip Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_state_skip_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_state_skip_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Attestation State Read Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_state_read_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_state_read_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Attestation Committee Building Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_committee_building_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_committee_building_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 },
   "options": {
    "content": "\n### Cache Hits/Misses\n\n\nRates of success/failure when trying the shuffling cache.\n"
   },
   "content": "\n### Cache Hits/Misses\n\n\nRates of success/failure when trying the shuffling cache.\n"
  },
  {
   "title": "Shuffling Cache Hits per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_shuffling_cache_hits_total[1m])"
    }
   ]
  },
  {
   "title": "Shuffling Cache Misses per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_shuffling_cache_misses_total[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "\n### Requests and Successes\n\n\nTracks the number of attestation processing requests and successes\n"
   },
   "content": "\n### Requests and Successes\n\n\nTracks the number of attestation processing requests and successes\n"
  },
  {
   "title": "Aggregated Attn. Processed per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_aggregated_attestation_processing_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Unaggregated Attn. Processed per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_unaggregated_attestation_processing_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Aggregated Attn. Success Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percentunit", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_aggregated_attestation_processing_successes_total / beacon_aggregated_attestation_processing_requests_total"
    }
   ]
  },
  {
   "title": "Unaggregated Attn. Success Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "percentunit", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_unaggregated_attestation_processing_successes_total / beacon_unaggregated_attestation_processing_requests_total"
    }
   ]
  }
 ]
}