{
 "title": "Gossipsub Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "options": {
    "content": "# Gossipsub Metrics\n\nVarious metrics monitoring gossip performance         "
   }
  },
  {
   "title": "Goosipsub Peers by Protocol",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gossipsub_peers_per_protocol", "legendFormat": "{{protocol}}" }
   ]
  },
  {
   "title": "Mesh peers per topic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_mesh_peers_per_main_topic",
     "legendFormat": "{{topic_hash}}"
    }
   ]
  },
  {
   "title": "Average Peer Score per Topic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_avg_peer_score_per_topic",
     "legendFormat": "{{topic_hash}}"
    }
   ]
  },
  {
   "title": "Attestations published per slot",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_attestations_published_per_subnet_per_slot",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "Subnets currently subscribed to",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "gossipsub_subscribed_subnets", "legendFormat": "{{subnet}}" }
   ]
  },
  {
   "title": "Mesh peers per subnet",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gossipsub_mesh_peers_per_subnet_topic",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "Subscribed Peers per subnet",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gossipsub_peers_per_subnet_topic_count",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "Average peer score per subnet",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gossipsub_avg_peer_score_per_subnet_topic",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "Failed attestations published per subnet",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_failed_attestation_published_per_subnet_per_slot",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "Failed publishes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gossipsub_failed_publishes_per_main_topic"
    }
   ]
  },
  {
   "title": "Relative number of scores below zero per client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_scores_below_zero_per_client",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Relative number of scores below gossip threshold per client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_scores_below_gossip_threshold_per_client",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Relative number of scores below publish threshold per client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_scores_below_publish_threshold_per_client",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Relative number of scores below greylist threshold per client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_scores_below_greylist_threshold_per_client",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Minimum scores per client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_min_scores_per_client",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Median scores per client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_median_scores_per_client",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Mean scores per client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_mean_scores_per_client",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Max scores per client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_max_scores_per_client",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "BeaconBlock mesh peers per client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "block_mesh_peers_per_client", "legendFormat": "{{Client}}" }
   ]
  },
  {
   "title": "BeaconAggregateAndProof mesh peers per client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beacon_aggregate_and_proof_mesh_peers_per_client",
     "legendFormat": "{{Client}}"
    }
   ]
  }
 ]
}