{
 "title": "Network",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Fork", "query": { "query": "label_values(hash)" } }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Health\n \n           " } },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_peers{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NAT",
   "type": "stat",
   "description": "Is the UDP port forwarded",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "nat_open{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Blocks Per Slot",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_topic_msg_recv_counts_total{hash=~\".*beacon_block.*\", instance=~\"$Instance\"}[$__rate_interval])*12"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "piechart",
   "description": "Peers via client implementations",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_peers_per_client{instance=~\"$Instance\"}",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Peer Type",
   "type": "piechart",
   "description": "Peers that have dialed us",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_inbound_peers{instance=~\"$Instance\"}",
     "legendFormat": "Inbound"
    },
    {
     "expr": "network_outbound_peers{instance=~\"$Instance\"}",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Total Libp2p Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_total_bandwidth{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Libp2p Inbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_inbound_bytes{instance=~\"$Instance\"}[1m])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Libp2p Outbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_outbound_bytes{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Average Peer Score Per Client",
   "type": "piechart",
   "description": "Average Peer score per client shifted by 100",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peer_score_per_client{instance=~\"$Instance\"}+100",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Peer Sync Status",
   "type": "piechart",
   "description": "Peers sync status",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_peers_per_status{instance=~\"$Instance\"}",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_total_bandwidth{instance=~\"$Instance\"}[$__rate_interval]) + rate(discovery_sent_bytes{instance=~\"$Instance\"}[$__rate_interval]) + rate(discovery_recv_bytes{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} bytes/s"
    }
   ]
  },
  {
   "title": "Discovery Inbound Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(discovery_recv_bytes{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Discovery Outbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(discovery_sent_bytes{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Peer Penalty Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "targets": [
    {
     "expr": "increase(libp2p_report_peer_msgs_total{instance=~\"$Instance\"}[1m])",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "# Discovery Metrics\n \n           "
   }
  },
  {
   "title": "Unsolicited Discovery Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "discovery_requests{instance=~\"$Instance\"}",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "Active Discv5 Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "discovery_sessions{instance=~\"$Instance\"}",
     "legendFormat": "active sessions"
    }
   ]
  },
  {
   "title": "Queued Discovery Queries",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "discovery_queue_size{instance=~\"$Instance\"}",
     "legendFormat": "Queued Discoveries"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 33 }, "options": { "content": "# RPC Metrics\n \n           " } },
  {
   "title": "Connected Peer Score Distribution",
   "type": "timeseries",
   "description": "Distribution of connected peer's score by quartile",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "peer_score_distribution{instance=~\"$Instance\"}",
     "legendFormat": "{{position}}"
    }
   ]
  },
  {
   "title": "RPC Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(libp2p_rpc_errors_per_client{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "Errors Per Second"
    }
   ]
  },
  {
   "title": "RPC Errors (Non timeout)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(libp2p_rpc_errors_per_client{rpc_error!~\"timeout\", instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{client}} - {{rpc_error}}"
    }
   ]
  },
  {
   "title": "10m Average RPC Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 42 },
   "targets": [
    {
     "expr": "rate(libp2p_rpc_requests_total{instance=~\"$Instance\"}[10m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RPC Timeouts Per Client",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "rate(libp2p_rpc_errors_per_client{rpc_error=~\"negotiation_timeout|stream_timeout\", instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{client}} -{{rpc_error}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 56 },
   "options": {
    "content": "# Gossipsub Metrics\n \n           "
   }
  },
  {
   "title": "Mesh Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "gossipsub_mesh_peer_counts{hash=~\".*beacon_aggregate_and_proof.*|.*beacon_block.*|.*sync_committee_contribution_and_proof.*\", instance=~\"$Instance\"}",
     "legendFormat": "{{hash}}"
    }
   ]
  },
  {
   "title": "Blocks Per Slot",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_topic_msg_recv_counts_total{hash=~\".*beacon_block.*\", instance=~\"$Instance\"}[$__rate_interval])*12"
    }
   ]
  },
  {
   "title": "Aggregated Attestations Per Slot",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_topic_msg_recv_counts_total{hash=~\".*beacon_aggregate_and_proof.*\", instance=~\"$Instance\"}[$__rate_interval])*12"
    }
   ]
  },
  {
   "title": "Invalid Messages Per Slot",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gossipsub_invalid_messages_per_topic{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "gauge",
   "description": "Cache Misses over a 10m window",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_memcache_misses_total{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Aggregate and Proof Peer Score",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_score_per_mesh_bucket{hash=~\".*beacon_aggregate_and_proof.*\", instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "10m Average of Block Delay from Start of Slot",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(beacon_block_gossip_slot_start_delay_time_bucket{instance=~\"$Instance\"}[10m])*12",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "IWANT Requests Per Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rate(gossipsub_topic_iwant_msgs_total{instance=~\"$Instance\", hash=~\"/eth2/$Fork/.*\"}[$__rate_interval])*12",
     "legendFormat": "{{hash}}"
    }
   ]
  },
  {
   "title": "30s Block Delay Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "rate(beacon_block_gossip_slot_start_delay_time_sum{instance=~\"$Instance\"}[30s])/rate(beacon_block_gossip_slot_start_delay_time_count{instance=~\"$Instance\"}[30s])",
     "legendFormat": "Block Delay"
    }
   ]
  },
  {
   "title": "Duplicates Filtered Per Slot",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "rate(gossipsub_topic_msg_recv_counts_unfiltered_total{hash=~\"/eth2/$Fork/beacon_aggregate_and_proof/ssz_snappy|/eth2/$Fork/beacon_block/ssz_snappy\", instance=~\"$Instance\"}[$__rate_interval])*12 - rate(gossipsub_topic_msg_recv_counts_total{hash=~\"/eth2/$Fork/beacon_aggregate_and_proof/ssz_snappy|/eth2/$Fork/beacon_block/ssz_snappy\", instance=~\"$Instance\"}[$__rate_interval])*12",
     "legendFormat": "{{hash}}"
    }
   ]
  },
  {
   "title": "Attestation Errors Per Slot",
   "type": "timeseries",
   "description": "Gossipsub Attestation Errors By Type",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "rate(gossipsub_attestation_errors_per_type[$__rate_interval])*12",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Gossip Penalties Per Slot",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "rate(gossipsub_scoring_penalties_total{instance=~\"$Instance\"}[$__rate_interval])*12",
     "legendFormat": "{{penalty}}"
    }
   ]
  },
  {
   "title": "Heartbeat Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "sum(rate(gossipsub_heartbeat_duration_sum{instance=~\"$Instance\"}[$__rate_interval]))/sum(rate(gossipsub_heartbeat_duration_count{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{Instance}}"
    }
   ]
  },
  {
   "title": "Accepted Messages Per Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "rate(gossipsub_accepted_messages_per_topic_total{hash=~\"/eth2/$Fork/.*\", instance=~\"$Instance\"}[$__rate_interval])*12",
     "legendFormat": "{{hash}}"
    }
   ]
  },
  {
   "title": "BeaconBlock Mesh Peers",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_mesh_peers_per_client{instance=~\"$Instance\"}",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "BeaconAggregateAndProof Mesh Peers",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_aggregate_and_proof_mesh_peers_per_client{instance=~\"$Instance\"}",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Recv Bytes per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_topic_msg_recv_bytes_total{hash=~\"/eth2/$Fork/.*\", instance=\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{hash}}"
    }
   ]
  },
  {
   "title": "Subscribed Peers Per Topic",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossipsub_topic_peers_counts{hash!~\".*attester_slashing.*|.*beacon_aggregate_and_proof.*|.*beacon_block.*|.*proposer_slashing.*|.*voluntary_exit.*|.*sync_committee_contribution_and_proof.*\", hash=~\"/eth2/$Fork/.*\", instance=~\"$Instance\"}",
     "legendFormat": "{{hash}}"
    }
   ]
  },
  {
   "title": "Sent Bytes per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_topic_msg_sent_bytes_total{hash=~\"/eth2/$Fork/.*\", instance=\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{hash}}"
    }
   ]
  },
  {
   "title": "Ignored Messages Per Slot",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 118 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_ignored_messages_per_topic_total{instance=~\"$Instance\"}[$__rate_interval])*12",
     "legendFormat": "{{hash}}"
    }
   ]
  },
  {
   "title": "Gossipsub Ignored Messages Per Client per Slot",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 118 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_unaccepted_messages_per_client{instance=~\"$Instance\"}[$__rate_interval])*12",
     "legendFormat": "{{client}}"
    }
   ]
  }
 ]
}