# Volume to persist data without accessible from host
volumes:
  prometheus_data:
    name: prometheus_data
  grafana_data:
    name: grarana_data

services:
  mainnet-execution:
    image: thorax/erigon:v2.30.0
    container_name: mainnet-execution
    volumes:
      - ./erigon/mainnet:/data
      - ./jwtsecret:/jwtsecret:ro
    command: |
      erigon
        --datadir=/data
        --chain=mainnet
        --snapshots=true
        --port=30303
        --http.port=8545
        --torrent.port=42069
        --metrics.port=6060
        --authrpc.port=8551
        --txpool.disable
        --http.addr=0.0.0.0
        --http.api="eth,erigon,debug,net,trace,web3"
        --torrent.download.rate="30mb"
        --metrics
        --metrics.addr=0.0.0.0
        --watch-the-burn
        --authrpc.jwtsecret=/jwtsecret
        --ws
        --authrpc.addr=0.0.0.0
        --authrpc.vhosts=*
        --externalcl
    ports:
      - 8545:8545  # expose localhost:8545
      - 30303:30303/tcp # expose localhost:30303
      - 30303:30303/udp
      - 42069:42069/tcp # expose localhost:42069
      - 42069:42069/udp
    expose:
      - 6060 # expose mainnet-execution:6060 to prometheus
      - 8551 # expose mainnet-execution:8551 to lighthouse
    restart: unless-stopped

  mainnet-beacon:
    image: sigp/lighthouse:latest-modern
    container_name: mainnet-beacon
    volumes:
      - ./lighthouse/mainnet:/root/.lighthouse
      - ./jwtsecret:/jwtsecret:ro
    command: |
      lighthouse bn
        --network=mainnet
        --http
        --http-address=0.0.0.0
        --http-port=5052
        --execution-endpoint=http://mainnet-execution:8551
        --execution-jwt=/jwtsecret
        --checkpoint-sync-url=https://beaconstate.ethstaker.cc
        --disable-deposit-contract-sync
        --metrics
        --metrics-address=0.0.0.0
        --metrics-allow-origin=*
        --metrics-port=5054
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 5052:5052
    expose:
      - 5054 # expose mainnet-beacon:5054 to prometheus
    restart: unless-stopped
    depends_on:
      - mainnet-execution

  gnosis-execution:
    image: nethermind/nethermind:latest
    container_name: gnosis-execution
    volumes:
      - ./gnosis/execution:/data
      - ./jwtsecret:/jwtsecret
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      --config=xdai
      --datadir=/data
      --log=INFO
      --Sync.SnapSync=false
      --JsonRpc.Enabled=true
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.Port=8546
      --JsonRpc.EnabledModules=[Web3,Eth,Subscribe,Net,]
      --JsonRpc.JwtSecretFile=/jwtsecret
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8552
      --Network.DiscoveryPort=30304
      --HealthChecks.Enabled=false
      --Pruning.CacheMb=2048
      --Metrics.Enabled=true
      --Discovery.Bootnodes=enode://a8558c4449bdb4ed47b8fd0ceaee8cf56272cd308e98e693a838d58b9abd2411b71b9b7e2d63a50b140fd9b0a2e05e83f338c3906dd925e9f178f0feda0c4ca7@165.232.138.187:30303,enode://e52280c512cd1f023135d7f70f31904bda7bb699d4300346182a2e3fc5a07637c25cc4349b48101ffe2fe6229b3b165ed7929ad9db971d847d02e21192989ce5@143.198.156.24:30303,enode://8ed1893f617f1ed2c6a978fa92fa38ac19db6de5596c93bf21921c40ed34f63b63a93234ddedf9b385192dd7aa652e1d4b55efed299961b0ae5d4318ecb985ec@159.223.213.61:30303,enode://cc3f99a19360edd73f91f04c6fe728ff8da431f8445a35c02a0fd99fee2be5d9f5ea75a416b08f4a019e0a0d3afa8aece93a560bbe3ce0509eec54bbddc00bb8@178.62.194.136:30303,enode://8f3a63b270cd32692f5b825874b9f3acef3cf90dec40fe54848267f568b7275349efb830812c1b24f1781774f745fb00e595d2feef642fd6867e173f05108cc4@178.62.192.195:30303,enode://075d567bcc5b6bbcb5c9922bf7f17a706408bed141dcefb5d387cfe6e0c7c9407e450a5d17b9180b25fb07b3e82943639d011752ea44a2d868b3c37f48a318b9@167.99.209.14:30303,enode://bb19f1fcf0d0667d9752bec2f4230e24331a7764e5a73a41006378861ef79f9a4386f646e239e1842e4bb721ade9369be8f2fd81b407d9febec2e150ccb7f257@137.184.228.83:30303,enode://529cc11acd013d5e92aa38d4139636619285b2bb4221bcdf7c5dbf171e828d05b88934e6154b984f8164953d7d7530b49c6d0e030fade3a3737d28092a289704@164.92.96.111:30303,enode://9d41c6f8c77a1ac3069cc9326068c04465b9fc56abaaf84fa753fc723511f278dd1d65c22753eb60dfd95f60fe942d0f670c490660e3d6cd518ddafb986682d2@178.62.196.104:30303,enode://874ac7df642fc2abffcca71991c3646a5634a415a4a6513112a89429f7ae43914ad6f1d2ea73a96a19f302c17a7c5e07a0dd01fed70c9294a6fd5615b86710b7@159.223.213.166:30303,enode://5d1a11b5f19afb7d2d04406a4877ed7de92a4ca898ee0d36ff54729b99664e4ac787877e553043a38a38f878aab43fc0d757673e0c11ee8eb606f1ea4681ce3c@147.182.204.197:30303,enode://144d125c790100f6405d957dea8c3a1647199109d915889e90d7f6c2940c8737b16e68e2a3af57327971ec28ed77408f9bc96035b2589da6496f3112ec72e037@137.184.183.65:30303,enode://ac8e8a62f5b54c35f4d7eb565079e9c81e241a150c0d6b2bb5bb32b068e8e4930b14a5b504f77d34014c8e9f14ec0307cc6b239e8c56be85fdcc68d4956cce7c@159.223.213.157:30303,enode://20b0de013d851ae5b667f41a923f2856420161fe0a46030cdea6d81db8da3c5b04070834219a2a6ca41d8f2c6c813870414ce473ab25736742163b0be6191861@159.223.209.185:30303,enode://3c8de197987eb896488ed60037b44c5201878d7cb47d22a322d6d73b999b1d5482820e0456dc08676665ba1ce96906900a2b5f830b2eea73730ca7532c227c7b@159.223.217.249:30303,enode://644ad8205801f9dba1d6eff107590d49479d5276c8d078f8631f351a2077d70b7bed2822219cb1c7590ba68149b89751968a45236e7d02c1025e493d647dd776@159.223.213.162:3030
    ports:
      - 30304:30304/tcp # p2p
      - 30304:30304/udp # p2p
    expose:
      - 8546 # gnosis-execution:8546
      - 8552 # gnosis-execution:8552 for beacon and validator
    restart: unless-stopped
    stop_grace_period: 2m

  gnosis-beacon:
    image: sigp/lighthouse:latest-modern
    container_name: gnosis-beacon
    volumes:
      - ./gnosis/consensus:/data
      - ./jwtsecret:/jwtsecret
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      lighthouse bn
        --network=gnosis
        --disable-upnp
        --datadir=/data
        --port=9001
        --http
        --http-address=0.0.0.0
        --http-port=4000
        --target-peers=50
        --execution-endpoint=http://gnosis-execution:8552
        --execution-jwt=/jwtsecret
        --debug-level=info
        --validator-monitor-auto
        --subscribe-all-subnets
        --import-all-attestations
        --metrics
        --metrics-port=5055
        --metrics-address=0.0.0.0
        --checkpoint-sync-url=https://checkpoint.gnosischain.com/
    ports:
      - 9001:9001/tcp # p2p
      - 9001:9001/udp # p2p
    expose:
      - 4000 # expose gnosis-beacon:4000 to validator
      - 5055 # expose gnosis-beacon:5055 to prometheus
    restart: unless-stopped
    stop_grace_period: 2m
    depends_on:
      - gnosis-execution

  gnosis-validators:
    image: sigp/lighthouse:latest-modern
    container_name: gnosis-validators
    volumes:
      - ./gnosis/consensus/validators:/data/validators
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      lighthouse vc
        --network=gnosis
        --datadir=/data
        --beacon-nodes=http://gnosis-beacon:4000
        --graffiti="pyk.sh"
        --debug-level=info
        --suggested-fee-recipient=0x17ae0a6BE2e97b384165626dB2569729d5006640
        --metrics
        --metrics-address=0.0.0.0
        --metrics-port=5064
    expose:
      - 5064 # expose gnosis-validators:5064 to prometheus
    restart: unless-stopped
    stop_grace_period: 2m
    depends_on:
      - gnosis-execution
      - gnosis-beacon

  goerli-execution:
    image: thorax/erigon:v2.30.0
    container_name: goerli-execution
    volumes:
      - ./goerli/execution:/data
      - ./jwtsecret:/jwtsecret:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      erigon
        --datadir=/data
        --chain=goerli
        --snapshots=true
        --port=30305
        --http.port=8546
        --torrent.port=42068
        --metrics.port=6060
        --authrpc.port=8551
        --txpool.disable
        --http.addr=0.0.0.0
        --http.api="eth,erigon,debug,net,trace,web3"
        --torrent.download.rate="30mb"
        --metrics
        --metrics.addr=0.0.0.0
        --authrpc.jwtsecret=/jwtsecret
        --ws
        --authrpc.addr=0.0.0.0
        --authrpc.vhosts=*
        --externalcl
        --prune.r.before=4367322
        --prune htc
    ports:
      - 8546:8546  # expose localhost:8546
      - 30305:30305/tcp # expose localhost:30305
      - 30305:30305/udp
      - 42068:42068/tcp # expose localhost:42068
      - 42068:42068/udp
    expose:
      - 6060 # expose goerli-execution:6060 to prometheus
      - 8551 # expose goerli-execution:8551 to lighthouse
    restart: unless-stopped
    stop_grace_period: 2m

  goerli-beacon:
    image: sigp/lighthouse:latest-modern
    container_name: goerli-beacon
    volumes:
      - ./goerli/consensus:/data
      - ./jwtsecret:/jwtsecret:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: |
      lighthouse bn
        --network=goerli
        --disable-upnp
        --datadir=/data
        --port=9002
        --http
        --http-address=0.0.0.0
        --http-port=5053
        --target-peers=50
        --execution-endpoint=http://goerli-execution:8551
        --execution-jwt=/jwtsecret
        --debug-level=info
        --validator-monitor-auto
        --subscribe-all-subnets
        --import-all-attestations
        --metrics
        --metrics-address=0.0.0.0
        --metrics-allow-origin=*
        --metrics-port=5054
        --checkpoint-sync-url=https://goerli.checkpoint-sync.ethpandaops.io
    ports:
      - 9002:9002/tcp # p2p
      - 9002:9002/udp # p2p
      - 5053:5053
    expose:
      - 5054 # expose goerli-beacon:5054 to prometheus
    restart: unless-stopped
    stop_grace_period: 2m
    depends_on:
      - goerli-execution

  # Non chains
  node-exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node-exporter
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
    expose:
      - 9100 # expose node-exporter:9100 to prometheus
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    privileged: true
    expose:
      - 8080
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.40.5
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090 # expose localhost:9090 and promtheus:9090 to grafana
    restart: unless-stopped
    depends_on:
      - mainnet-execution
      - mainnet-beacon
      - cadvisor
      - node-exporter
      - gnosis-execution
      - gnosis-beacon
      - gnosis-validators
      - goerli-execution
      - goerli-beacon

  grafana:
    image: grafana/grafana-oss:9.3.1
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000" # expose localhost:3000
    depends_on:
      - prometheus

