global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    scheme: http
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "execution-nodes"
    metrics_path: /debug/metrics/prometheus
    scheme: http
    scrape_interval: 5s
    static_configs:
      - targets: ["mainnet-execution:6060"]

  - job_name: "beacon-nodes"
    scrape_interval: 5s
    static_configs:
      - targets:
        - "mainnet-beacon:5054"
        - "gnosis-beacon:5055"
        - "gnosis-validators:5064"

