global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    scheme: http
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "erigon-mainnet"
    metrics_path: /debug/metrics/prometheus
    scheme: http
    scrape_interval: 5s
    static_configs:
      - targets: ["erigon-mainnet:6060"]

  - job_name: "lighthouse"
    scrape_interval: 5s
    static_configs:
      - targets: ["lighthouse-mainnet:5054"]

  - job_name: "gnosis-lighthouse"
    scrape_interval: 5s
    static_configs:
      - targets: ["gnosis-lighthouse-beacon:5055", "gnosis-lighthouse-validator:5064"]

